version: "3"
services:
  pgadmin4:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@mail.ru
        PGADMIN_DEFAULT_PASSWORD: QwertY09
    ports:
      - 5050:80
    networks:
      - backend   
    restart: always
  
  pg-db:
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
      - 7070:5432
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
 
networks:
  backend:

volumes:
  pg-db-data:
